from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("opt-in/", views.opt_in, name="opt_in"),
    path("results/", views.results, name="results"),
    path("withdraw/", views.withdraw_allotment, name="withdraw"),
    path("upload/", views.upload_results, name="upload_results"),
    path("download-sample-csv/", views.download_sample_csv, name="download_sample_csv"),
    path("api/seats/", views.seat_status, name="seat_status"),
    path("api/analytics/", views.analytics_data, name="analytics_data"),
    path("api/mark-popup-seen/", views.mark_popup_seen, name="mark_popup_seen"),
    path("api/check-confirmations/", views.check_new_confirmations, name="check_new_confirmations"),
    path("analytics/", views.analytics_dashboard, name="analytics"),
    path("admin-panel/", views.admin_panel, name="admin_panel"),
    path("run-allotment/", views.run_allotment, name="run_allotment"),
    path("export/csv/", views.export_allotment_csv, name="export_csv"),
    path("export/pdf/", views.export_allotment_pdf, name="export_allotment_pdf"),
    path("admin/force-confirm/<int:allotment_id>/", views.admin_force_confirm, name="admin_force_confirm"),
    path("admin/reset-waitlist/<int:allotment_id>/", views.admin_reset_waitlist, name="admin_reset_waitlist"),
    path("admin/reassign/<int:student_id>/", views.admin_reassign, name="admin_reassign"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    path("api/admin-live/", views.admin_live_data, name="admin_live_data"),
    
]