services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn elective_portal.wsgi:application"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False