# Generated by Django 6.0.4 on 2026-04-28 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('faculty', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField(default=60)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('semester', models.IntegerField(default=6)),
                ('branch', models.CharField(default='CSE', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectivePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(1, '1st Choice'), (2, '2nd Choice'), (3, '3rd Choice')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.elective')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.studentprofile')),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('student', 'elective'), ('student', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('NOT_ALLOTTED', 'Not Allotted')], default='NOT_ALLOTTED', max_length=20)),
                ('allotted_at', models.DateTimeField(auto_now_add=True)),
                ('preference_rank_given', models.IntegerField(blank=True, null=True)),
                ('elective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electives.elective')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electives.studentprofile')),
            ],
            options={
                'unique_together': {('student',)},
            },
        ),
    ]
