# Generated by Django 6.0.4 on 2026-04-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0003_alter_elective_branch_quota_alter_result_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allotment',
            name='is_admin_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allotment',
            name='popup_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allotment',
            name='waitlist_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elective',
            name='branch_quota',
            field=models.JSONField(blank=True, default=dict, help_text='Branch-wise seat quota. Example: {"CSE": 40, "ISE": 15, "ECE": 5}.'),
        ),
    ]
