# Generated by Django 6.0.4 on 2026-04-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0004_allotment_admin_note_allotment_is_admin_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allotment',
            name='pending_choice',
            field=models.BooleanField(default=False),
        ),
    ]
